import {
  User01,
  Mail01,
  Phone01,
  MarkerPin01,
  Globe01,
  Briefcase01,
  GraduationHat01,
  Stars01,
  File06,
  Award01,
  Heart,
  Edit03,
} from "@untitledui/icons";
import type { TemplateStyles, WizardStep } from "./types";

export const BLOCK_META: Record<
  string,
  { icon: React.ComponentType<{ className?: string }>; label: string }
> = {
  header: { icon: User01, label: "Header" },
  contact: { icon: Mail01, label: "Contact" },
  summary: { icon: File06, label: "Summary" },
  experience: { icon: Briefcase01, label: "Experience" },
  education: { icon: GraduationHat01, label: "Education" },
  skills: { icon: Stars01, label: "Skills" },
  projects: { icon: Edit03, label: "Projects" },
  certifications: { icon: Award01, label: "Certificates" },
  awards: { icon: Award01, label: "Awards & Achievements" },
  languages: { icon: Globe01, label: "Languages" },
  volunteer: { icon: Heart, label: "Volunteer Experience" },
  publications: { icon: File06, label: "Publications" },
  interests: { icon: Heart, label: "Interests" },
  custom: { icon: Edit03, label: "Custom Section" },
};

export const SUGGESTED_SECTIONS = [
  "projects",
  "certifications",
  "awards",
  "languages",
  "volunteer",
  "publications",
  "interests",
];

export const CONTACT_FIELDS: {
  key: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
}[] = [
  { key: "email", label: "Email", icon: Mail01 },
  { key: "phone", label: "Phone", icon: Phone01 },
  { key: "location", label: "Location", icon: MarkerPin01 },
  { key: "website", label: "Website", icon: Globe01 },
  { key: "linkedin", label: "LinkedIn", icon: Globe01 },
];

export const CONTACT_FIELDS_LIST = [
  { key: "email", label: "Email" },
  { key: "phone", label: "Phone" },
  { key: "location", label: "Location" },
  { key: "website", label: "Website" },
  { key: "linkedin", label: "LinkedIn" },
];

export const TEMPLATES: TemplateStyles[] = [
  /* ═══════════════════ SINGLE COLUMN (5) ═══════════════════ */

  {
    id: "modern-clean",
    name: "Modern Clean",
    description: "Clean single-column layout with centered header and inline skills. Perfect for tech and design roles.",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headerAlignment: "left",
    contactLayout: "inline",
    headingStyle: "underline",
    skillsStyle: "inline",
    accentColor: "#111827",
    layout: "single",
    showTimeline: true,
    dividerStyle: "line",
  },
  {
    id: "ivy-league",
    name: "Ivy League",
    description: "Classic serif-driven design favored by recruiters at top firms. Conservative and timeless.",
    headingFont: "'Georgia', serif",
    bodyFont: "'Georgia', serif",
    headerAlignment: "center",
    contactLayout: "inline",
    headingStyle: "bold",
    skillsStyle: "inline",
    accentColor: "#1F2937",
    layout: "single",
    showTimeline: false,
    dividerStyle: "line",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Ultra-clean design with generous whitespace and thin dividers. Lets your content breathe.",
    headingFont: "'Lato', sans-serif",
    bodyFont: "'Lato', sans-serif",
    headerAlignment: "left",
    contactLayout: "inline",
    headingStyle: "caps-spaced",
    skillsStyle: "inline",
    accentColor: "#64748B",
    layout: "single",
    showTimeline: false,
    dividerStyle: "line",
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Visual timeline layout emphasizing career progression. Great for experienced professionals.",
    headingFont: "'Montserrat', sans-serif",
    bodyFont: "'Open Sans', sans-serif",
    headerAlignment: "left",
    contactLayout: "inline",
    headingStyle: "colored-bg",
    skillsStyle: "tags",
    accentColor: "#0D5E4F",
    layout: "single",
    showTimeline: true,
    dividerStyle: "none",
  },
  {
    id: "compact",
    name: "Compact",
    description: "Condensed layout that fits more content on a single page. Ideal for senior professionals with extensive experience.",
    headingFont: "'Roboto', sans-serif",
    bodyFont: "'Roboto', sans-serif",
    headerAlignment: "left",
    contactLayout: "two-column",
    headingStyle: "bordered-left",
    skillsStyle: "inline",
    accentColor: "#374151",
    layout: "single",
    showTimeline: false,
    dividerStyle: "none",
    compactMode: true,
  },

  /* ═══════════════════ TWO COLUMN (5) ═══════════════════ */

  {
    id: "executive",
    name: "Executive",
    description: "Professional sidebar layout with contact and skills on the left. Clean and authoritative for leadership roles.",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    headerAlignment: "left",
    contactLayout: "column",
    headingStyle: "bold",
    skillsStyle: "list",
    accentColor: "#1E3A5F",
    layout: "two-column",
    sidebarPosition: "left",
    sidebarWidth: 35,
    sidebarBlocks: ["contact", "skills", "languages", "certifications", "interests"],
    sidebarBgColor: "#F8FAFC",
    headerSpan: "full",
    showTimeline: false,
    dividerStyle: "none",
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Sophisticated design with a tinted sidebar and serif headings. Ideal for consulting and client-facing roles.",
    headingFont: "'Playfair Display', serif",
    bodyFont: "'Lato', sans-serif",
    headerAlignment: "left",
    contactLayout: "column",
    headingStyle: "underline",
    skillsStyle: "bars",
    accentColor: "#4C1D95",
    layout: "two-column",
    sidebarPosition: "left",
    sidebarWidth: 32,
    sidebarBlocks: ["contact", "skills", "languages", "interests"],
    sidebarBgColor: "#F5F3FF",
    headerSpan: "full",
    showTimeline: false,
    dividerStyle: "line",
  },
  {
    id: "creative",
    name: "Creative",
    description: "Bold colored header with a modern two-column body. Designed for marketing, design, and creative fields.",
    headingFont: "'Poppins', sans-serif",
    bodyFont: "'Open Sans', sans-serif",
    headerAlignment: "left",
    contactLayout: "column",
    headingStyle: "colored-bg",
    skillsStyle: "tags",
    accentColor: "#059669",
    layout: "two-column",
    sidebarPosition: "right",
    sidebarWidth: 33,
    sidebarBlocks: ["contact", "skills", "languages", "interests", "certifications"],
    headerSpan: "full",
    headerBgColor: "#059669",
    headerTextColor: "#FFFFFF",
    showTimeline: false,
    dividerStyle: "none",
  },
  {
    id: "contemporary",
    name: "Contemporary",
    description: "Modern balanced two-column design with clean lines. Versatile for startups and forward-thinking companies.",
    headingFont: "'Work Sans', sans-serif",
    bodyFont: "'Work Sans', sans-serif",
    headerAlignment: "left",
    contactLayout: "column",
    headingStyle: "caps-spaced",
    skillsStyle: "tags",
    accentColor: "#0F766E",
    layout: "two-column",
    sidebarPosition: "left",
    sidebarWidth: 34,
    sidebarBlocks: ["contact", "summary", "skills", "languages", "interests"],
    sidebarBgColor: "#0F766E",
    sidebarTextColor: "#FFFFFF",
    headerSpan: "main",
    showTimeline: true,
    dividerStyle: "none",
  },
  {
    id: "professional",
    name: "Professional",
    description: "Classic balanced two-column with a subtle divider. The safe, versatile choice for any industry.",
    headingFont: "'Source Sans 3', sans-serif",
    bodyFont: "'Source Sans 3', sans-serif",
    headerAlignment: "center",
    contactLayout: "inline",
    headingStyle: "bordered-left",
    skillsStyle: "list",
    accentColor: "#1E3A5F",
    layout: "two-column",
    sidebarPosition: "left",
    sidebarWidth: 35,
    sidebarBlocks: ["contact", "skills", "languages", "certifications", "interests"],
    headerSpan: "full",
    showTimeline: false,
    dividerStyle: "line",
  },
];

export const DEFAULT_CONTENT: Record<string, Record<string, unknown>> = {
  experience: { items: [] },
  education: { items: [] },
  projects: { items: [] },
  certifications: { items: [] },
  awards: { items: [] },
  volunteer: { items: [] },
  publications: { items: [] },
  skills: { items: [] },
  languages: { items: [] },
  interests: { items: [] },
  summary: { text: "" },
  header: { name: "", title: "", summary: "", headerImage: "", headerImageShape: "circle", website: "" },
  contact: { email: "", phone: "", location: "", website: "", linkedin: "" },
  custom: { text: "" },
};

export const ZOOM_OPTIONS = [
  { label: "50%", value: 0.5 },
  { label: "75%", value: 0.75 },
  { label: "100%", value: 1 },
  { label: "125%", value: 1.25 },
  { label: "150%", value: 1.5 },
];

export const WIZARD_STEPS: WizardStep[] = [
  {
    id: 1,
    label: "Personal details",
    description: "Please provide your name and email",
    blockTypes: ["header", "contact"],
  },
  {
    id: 2,
    label: "Short profile summary",
    description: "A few details about your candidature",
    blockTypes: ["summary"],
  },
  {
    id: 3,
    label: "Work experience",
    description: "Mention all your work experience",
    blockTypes: ["experience"],
  },
  {
    id: 4,
    label: "Education",
    description: "Mention all your academic details",
    blockTypes: ["education"],
  },
  {
    id: 5,
    label: "Skills",
    description: "Mention all relevant skills that you have",
    blockTypes: ["skills"],
  },
  {
    id: 6,
    label: "Resume templates",
    description: "Pick the best or recommended template",
    blockTypes: [],
  },
];
